# Generated by Django 6.1.1 on 2026-09-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['department'], name='employees_e_departm_e28f46_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['is_active'], name='employees_e_is_acti_ff761b_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['salary'], name='employees_e_salary_63d04b_idx'),
        ),
    ]
