# Generated by Django 6.1.1 on 2026-09-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_employees_e_departm_e28f46_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_departm_e28f46_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_is_acti_ff761b_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_salary_63d04b_idx',
        ),
    ]
