# Generated by Django 6.1.1 on 2026-09-28 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_projects'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='COMPLETED', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='employees.employee')),
                ('from_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', to='employees.department')),
                ('to_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', to='employees.department')),
                ('transferred_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
